
-- 1. Main Question Bank Table
CREATE TABLE IF NOT EXISTS questions_master (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    question_type VARCHAR(50) DEFAULT 'MCQ', -- MCQ / TrueFalse / Numeric / Descriptive
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    correct_answer VARCHAR(10), -- A/B/C/D or value
    answer_explanation TEXT,
    subject_name VARCHAR(100),
    topic_name VARCHAR(150),
    sub_topic_name VARCHAR(150),
    difficulty_level VARCHAR(20) DEFAULT 'Medium', -- Easy / Medium / Hard
    language_type VARCHAR(20) DEFAULT 'Bilingual', -- Hindi / English / Bilingual
    exam_category VARCHAR(100),
    created_by_user_id BIGINT,
    question_source VARCHAR(50) DEFAULT 'Manual', -- Manual / BulkUpload / AI
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Bulk Upload Batches
CREATE TABLE IF NOT EXISTS bulk_upload_batches (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploaded_by_user_id BIGINT,
    upload_file_name VARCHAR(255),
    upload_file_type VARCHAR(20),
    total_rows_found INT DEFAULT 0,
    total_questions_saved INT DEFAULT 0,
    total_failed_rows INT DEFAULT 0,
    upload_status VARCHAR(30) DEFAULT 'Processing', -- Processing / Completed / Failed
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Bulk Upload Rows (Error Tracking)
CREATE TABLE IF NOT EXISTS bulk_upload_rows (
    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT REFERENCES bulk_upload_batches(batch_id) ON DELETE CASCADE,
    row_number INT,
    raw_question_text TEXT,
    error_message TEXT,
    error_type VARCHAR(100),
    is_fixed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Subjects Master
CREATE TABLE IF NOT EXISTS subjects_master (
    subject_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name VARCHAR(100) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

-- 5. Topics Master
CREATE TABLE IF NOT EXISTS topics_master (
    topic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id INT REFERENCES subjects_master(subject_id) ON DELETE CASCADE,
    topic_name VARCHAR(150) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

-- 6. Question Tags
CREATE TABLE IF NOT EXISTS question_tags (
    tag_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. Question Tag Mapping
CREATE TABLE IF NOT EXISTS question_tag_mapping (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES questions_master(question_id) ON DELETE CASCADE,
    tag_id INT REFERENCES question_tags(tag_id) ON DELETE CASCADE
);

-- 8. Users Master (Optional - usually auth.users is sufficient, but creating as requested)
CREATE TABLE IF NOT EXISTS users_master (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(150),
    user_role VARCHAR(30) DEFAULT 'Creator', -- Admin / Creator / Teacher
    email VARCHAR(150) UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. AI Processing Logs
CREATE TABLE IF NOT EXISTS ai_processing_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES questions_master(question_id) ON DELETE SET NULL,
    ai_action_type VARCHAR(100), -- GrammarFix / ExplanationGen
    ai_input_text TEXT,
    ai_output_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- RLS Policies (Open availability for now as per previous pattern, can be tightened later)
ALTER TABLE questions_master ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON questions_master FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE bulk_upload_batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON bulk_upload_batches FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE bulk_upload_rows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON bulk_upload_rows FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE subjects_master ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON subjects_master FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE topics_master ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON topics_master FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE question_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON question_tags FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE question_tag_mapping ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON question_tag_mapping FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE users_master ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON users_master FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE ai_processing_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON ai_processing_logs FOR ALL USING (true) WITH CHECK (true);
