import PptxGenJS from 'pptxgenjs';
import { Question } from '../types';

export interface PPTExportOptions {
    title: string;
    subtitle?: string;
    theme?: 'dark' | 'light' | 'colorful';
    includeTimer?: boolean;
    timerDuration?: number; // in seconds
    showAnswerAfterEach?: boolean;
    includeExplanations?: boolean;
    authorName?: string;
}

export const generateQuestionSetPPT = async (
    questions: Question[],
    options: PPTExportOptions
): Promise<void> => {
    const pptx = new PptxGenJS();
    const {
        title,
        subtitle,
        theme = 'dark',
        showAnswerAfterEach = true,
        includeExplanations = true,
        authorName = 'Q-Bank Pro'
    } = options;

    // Theme configuration
    const themes = {
        dark: {
            bg: '111827', // slate-900
            fg: 'F3F4F6', // slate-100
            accent: '6366F1', // indigo-500
            secondary: '9CA3AF' // slate-400
        },
        light: {
            bg: 'FFFFFF',
            fg: '1F2937', // slate-800
            accent: '2563EB', // blue-600
            secondary: '4B5563' // slate-600
        },
        colorful: {
            bg: 'F0Fdf4', // green-50
            fg: '166534', // green-800
            accent: 'D97706', // amber-600
            secondary: '15803d' // green-700
        }
    };

    const colors = themes[theme];

    // 1. Title Slide
    const slideTitle = pptx.addSlide();
    slideTitle.background = { color: colors.bg };

    slideTitle.addText(title, {
        x: '10%', y: '40%', w: '80%', h: 1.5,
        fontSize: 44,
        color: colors.fg,
        bold: true,
        align: 'center',
        fontFace: 'Arial'
    });

    if (subtitle) {
        slideTitle.addText(subtitle, {
            x: '10%', y: '55%', w: '80%', h: 0.5,
            fontSize: 24,
            color: colors.secondary,
            align: 'center',
            fontFace: 'Arial'
        });
    }

    slideTitle.addText(`Generated by ${authorName}`, {
        x: '10%', y: '90%', w: '80%', h: 0.3,
        fontSize: 12,
        color: colors.secondary,
        align: 'center',
        fontFace: 'Arial'
    });

    // 2. Question Slides
    questions.forEach((q, index) => {
        // Question Slide
        const slide = pptx.addSlide();
        slide.background = { color: colors.bg };

        // Header (Q Number)
        slide.addText(`Question ${index + 1}`, {
            x: 0.5, y: 0.3, w: '20%', h: 0.4,
            fontSize: 14,
            color: colors.accent,
            bold: true
        });

        // Difficulty Badge
        slide.addShape(pptx.ShapeType.roundRect, {
            x: '85%', y: 0.3, w: 1.5, h: 0.4,
            fill: { color: colors.accent },
            rectRadius: 0.2
        });
        slide.addText(q.difficulty || 'Medium', {
            x: '85%', y: 0.3, w: 1.5, h: 0.4,
            fontSize: 12,
            color: 'FFFFFF',
            align: 'center'
        });

        // Question Text
        slide.addText(q.question_eng, {
            x: 0.5, y: 1.0, w: '90%', h: 1.5,
            fontSize: 24,
            color: colors.fg,
            valign: 'top',
            fontFace: 'Arial',
            shrinkText: true
        });

        // Hindi translation if available
        if (q.question_hin) {
            slide.addText(q.question_hin, {
                x: 0.5, y: 2.5, w: '90%', h: 1.0,
                fontSize: 20,
                color: colors.secondary,
                valign: 'top',
                fontFace: 'Mangal', // Standard Hindi font
                shrinkText: true
            });
        }

        // Options
        const optionsYStart = q.question_hin ? 3.8 : 3.0;
        const opts = [
            { l: 'A', t: q.option1_eng },
            { l: 'B', t: q.option2_eng },
            { l: 'C', t: q.option3_eng },
            { l: 'D', t: q.option4_eng }
        ];
        if (q.option5_eng) opts.push({ l: 'E', t: q.option5_eng });

        opts.forEach((opt, i) => {
            const yPos = optionsYStart + (i * 0.7);

            // Bullet/Label
            slide.addShape(pptx.ShapeType.ellipse, {
                x: 0.6, y: yPos, w: 0.4, h: 0.4,
                fill: { color: colors.secondary, transparency: 80 },
                line: { color: colors.secondary, width: 1 }
            });
            slide.addText(opt.l, {
                x: 0.6, y: yPos, w: 0.4, h: 0.4,
                fontSize: 14,
                color: colors.fg,
                align: 'center',
                bold: true
            });

            // Option Text
            slide.addText(opt.t, {
                x: 1.2, y: yPos, w: '80%', h: 0.4,
                fontSize: 18,
                color: colors.fg
            });
        });

        // Answer Slide (if enabled)
        if (showAnswerAfterEach) {
            const ansSlide = pptx.addSlide();
            ansSlide.background = { color: colors.bg };

            // Re-add Title
            ansSlide.addText(`Answer: Question ${index + 1}`, {
                x: 0.5, y: 0.3, w: '50%', h: 0.4,
                fontSize: 14,
                color: colors.secondary
            });

            // Big Correct Option
            const ansIdx = parseInt(q.answer) - 1 || 0;
            const ansLabel = String.fromCharCode(65 + ansIdx); // A, B, C...
            const ansText = opts[ansIdx]?.t || 'Unknown';

            ansSlide.addShape(pptx.ShapeType.rect, {
                x: 1.0, y: 1.5, w: 8.0, h: 2.0,
                fill: { color: '10B981' }, // Success green
                rectRadius: 0.2
            });

            ansSlide.addText(`${ansLabel}. ${ansText}`, {
                x: 1.0, y: 1.5, w: 8.0, h: 2.0,
                fontSize: 32,
                color: 'FFFFFF',
                align: 'center',
                bold: true
            });

            // Explanation
            if (includeExplanations && q.solution_eng) {
                ansSlide.addShape(pptx.ShapeType.rect, {
                    x: 1.0, y: 4.0, w: 8.0, h: 2.5,
                    fill: { color: colors.fg, transparency: 90 },
                    line: { color: colors.secondary, width: 1, dashType: 'dash' }
                });

                ansSlide.addText('Explanation:', {
                    x: 1.2, y: 4.1, w: 2.0, h: 0.4,
                    fontSize: 14,
                    color: colors.accent,
                    bold: true
                });

                ansSlide.addText(q.solution_eng, {
                    x: 1.2, y: 4.6, w: 7.6, h: 1.8,
                    fontSize: 14,
                    color: colors.fg,
                    valign: 'top'
                });
            }
        }
    });

    // End Slide
    const endSlide = pptx.addSlide();
    endSlide.background = { color: colors.bg };

    endSlide.addText('Thank You!', {
        x: '30%', y: '40%', w: '40%', h: 1.0,
        fontSize: 50,
        color: colors.accent,
        bold: true,
        align: 'center'
    });

    // Save the PPT
    const filename = `${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pptx`;
    await pptx.writeFile({ fileName: filename });
};
